backend:
  unleash:
    instanceNamespace: bifrost-unleash

    sqlInstanceId: foo
    sqlInstanceAddress: 1.2.3.4
    sqlInstanceRegion: foo

    googleServiceAccountEmail: foo@bar
    kubernetesServiceAccountName: foo

    webIngressClass: foo
    webIngressHost: foo.bar
    webOAuthJWTAudience: foo

    apiIngressClass: foo
    apiIngressHost: foo.bar

    teamsApiToken: foo

    # Channel migration example config (disabled by default)
    channelMigration:
      enabled: false
      map: "stable-v5:stable-v6,rapid-v5:rapid-v6"
      healthTimeout: "5m"
      delay: "30s"

  google:
    projectId: foo
    projectNumber: 123
    serviceAccountEmail: foo@bar
    iapBackendServiceId: 123

  teams:
    apiToken: foo

ingress:
  host: foo.bar

networkPolicy:
  apiServerCIDR: 1.2.3.4/32